<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Fce28iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Fce28i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Fce28i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialite' => ['privates', '.errored..service_locator..Fce28i.App\\Entity\\Specialites', NULL, 'Cannot autowire service ".service_locator..Fce28i": it needs an instance of "App\\Entity\\Specialites" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'specialite' => 'App\\Entity\\Specialites',
            'entityManager' => '?',
        ]);
    }
}
