<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDahirasControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fvw2iuG.App\Controller\DahirasController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fvw2iuG.App\\Controller\\DahirasController::delete()'] = ($container->privates['.service_locator.fvw2iuG'] ?? $container->load('get_ServiceLocator_Fvw2iuGService'))->withContext('App\\Controller\\DahirasController::delete()', $container);
    }
}
