<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReunionControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R77Zl9c.App\Controller\ReunionController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R77Zl9c.App\\Controller\\ReunionController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'membresRepository' => ['privates', 'App\\Repository\\MembresRepository', 'getMembresRepositoryService', true],
        ], [
            'entityManager' => '?',
            'membresRepository' => 'App\\Repository\\MembresRepository',
        ]))->withContext('App\\Controller\\ReunionController::new()', $container);
    }
}
