<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReunionControllerimpressionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8U2gOPW.App\Controller\ReunionController::impression()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8U2gOPW.App\\Controller\\ReunionController::impression()'] = ($container->privates['.service_locator.8U2gOPW'] ?? $container->load('get_ServiceLocator_8U2gOPWService'))->withContext('App\\Controller\\ReunionController::impression()', $container);
    }
}
