<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialitesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MtxOC_2.App\Controller\SpecialitesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MtxOC_2.App\\Controller\\SpecialitesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialitesRepository' => ['privates', 'App\\Repository\\SpecialitesRepository', 'getSpecialitesRepositoryService', true],
        ], [
            'specialitesRepository' => 'App\\Repository\\SpecialitesRepository',
        ]))->withContext('App\\Controller\\SpecialitesController::index()', $container);
    }
}
