<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cs1EDC..App\Controller\ThemesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cs1EDC..App\\Controller\\ThemesController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'theme' => ['privates', '.errored..service_locator.Cs1EDC..App\\Entity\\Themes', NULL, 'Cannot autowire service ".service_locator.Cs1EDC.": it needs an instance of "App\\Entity\\Themes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'theme' => 'App\\Entity\\Themes',
        ]))->withContext('App\\Controller\\ThemesController::show()', $container);
    }
}
