<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uvnGCMZ.App\Controller\ThemesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uvnGCMZ.App\\Controller\\ThemesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'themesRepository' => ['privates', 'App\\Repository\\ThemesRepository', 'getThemesRepositoryService', true],
        ], [
            'themesRepository' => 'App\\Repository\\ThemesRepository',
        ]))->withContext('App\\Controller\\ThemesController::index()', $container);
    }
}
