<?php

namespace ContainerX2xmdxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S53iC1x.App\Entity\Themes' shared service.
     *
     * @return \App\Entity\Themes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.S53iC1x": it needs an instance of "App\\Entity\\Themes" but this type has been excluded in "config/services.yaml".');
    }
}
