<?php

namespace ContainerAq9Kqjs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CO52nPYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CO52nPY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CO52nPY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DahirasController::index' => ['privates', '.service_locator.Dy2gcLh.App\\Controller\\DahirasController::index()', 'getDahirasControllerindexService', true],
            'App\\Controller\\DahirasController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DahirasController::new()', 'getDahirasControllernewService', true],
            'App\\Controller\\DahirasController::show' => ['privates', '.service_locator.4sMFoOA.App\\Controller\\DahirasController::show()', 'getDahirasControllershowService', true],
            'App\\Controller\\DahirasController::edit' => ['privates', '.service_locator.fvw2iuG.App\\Controller\\DahirasController::edit()', 'getDahirasControllereditService', true],
            'App\\Controller\\DahirasController::delete' => ['privates', '.service_locator.fvw2iuG.App\\Controller\\DahirasController::delete()', 'getDahirasControllerdeleteService', true],
            'App\\Controller\\EncadreurController::index' => ['privates', '.service_locator.50_YF0x.App\\Controller\\EncadreurController::index()', 'getEncadreurControllerindexService', true],
            'App\\Controller\\EncadreurController::new' => ['privates', '.service_locator.xBM8bnR.App\\Controller\\EncadreurController::new()', 'getEncadreurControllernewService', true],
            'App\\Controller\\EncadreurController::show' => ['privates', '.service_locator.YukPcYQ.App\\Controller\\EncadreurController::show()', 'getEncadreurControllershowService', true],
            'App\\Controller\\EncadreurController::edit' => ['privates', '.service_locator.Q_9eqzw.App\\Controller\\EncadreurController::edit()', 'getEncadreurControllereditService', true],
            'App\\Controller\\EncadreurController::delete' => ['privates', '.service_locator.Q_9eqzw.App\\Controller\\EncadreurController::delete()', 'getEncadreurControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.qYO1FzE.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.SSsS_et.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.D.nMOje.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.2DjqodR.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.JTVina6.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::state' => ['privates', '.service_locator.067pOr..App\\Controller\\UserController::state()', 'getUserControllerstateService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\DahirasController:index' => ['privates', '.service_locator.Dy2gcLh.App\\Controller\\DahirasController::index()', 'getDahirasControllerindexService', true],
            'App\\Controller\\DahirasController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DahirasController::new()', 'getDahirasControllernewService', true],
            'App\\Controller\\DahirasController:show' => ['privates', '.service_locator.4sMFoOA.App\\Controller\\DahirasController::show()', 'getDahirasControllershowService', true],
            'App\\Controller\\DahirasController:edit' => ['privates', '.service_locator.fvw2iuG.App\\Controller\\DahirasController::edit()', 'getDahirasControllereditService', true],
            'App\\Controller\\DahirasController:delete' => ['privates', '.service_locator.fvw2iuG.App\\Controller\\DahirasController::delete()', 'getDahirasControllerdeleteService', true],
            'App\\Controller\\EncadreurController:index' => ['privates', '.service_locator.50_YF0x.App\\Controller\\EncadreurController::index()', 'getEncadreurControllerindexService', true],
            'App\\Controller\\EncadreurController:new' => ['privates', '.service_locator.xBM8bnR.App\\Controller\\EncadreurController::new()', 'getEncadreurControllernewService', true],
            'App\\Controller\\EncadreurController:show' => ['privates', '.service_locator.YukPcYQ.App\\Controller\\EncadreurController::show()', 'getEncadreurControllershowService', true],
            'App\\Controller\\EncadreurController:edit' => ['privates', '.service_locator.Q_9eqzw.App\\Controller\\EncadreurController::edit()', 'getEncadreurControllereditService', true],
            'App\\Controller\\EncadreurController:delete' => ['privates', '.service_locator.Q_9eqzw.App\\Controller\\EncadreurController::delete()', 'getEncadreurControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.qYO1FzE.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.SSsS_et.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.D.nMOje.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.2DjqodR.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.JTVina6.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.hKA2je_.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:state' => ['privates', '.service_locator.067pOr..App\\Controller\\UserController::state()', 'getUserControllerstateService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.nLtHlEw.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DahirasController::index' => '?',
            'App\\Controller\\DahirasController::new' => '?',
            'App\\Controller\\DahirasController::show' => '?',
            'App\\Controller\\DahirasController::edit' => '?',
            'App\\Controller\\DahirasController::delete' => '?',
            'App\\Controller\\EncadreurController::index' => '?',
            'App\\Controller\\EncadreurController::new' => '?',
            'App\\Controller\\EncadreurController::show' => '?',
            'App\\Controller\\EncadreurController::edit' => '?',
            'App\\Controller\\EncadreurController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::state' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DahirasController:index' => '?',
            'App\\Controller\\DahirasController:new' => '?',
            'App\\Controller\\DahirasController:show' => '?',
            'App\\Controller\\DahirasController:edit' => '?',
            'App\\Controller\\DahirasController:delete' => '?',
            'App\\Controller\\EncadreurController:index' => '?',
            'App\\Controller\\EncadreurController:new' => '?',
            'App\\Controller\\EncadreurController:show' => '?',
            'App\\Controller\\EncadreurController:edit' => '?',
            'App\\Controller\\EncadreurController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:state' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
