<?php

namespace ContainerAq9Kqjs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncadreurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q_9eqzw.App\Controller\EncadreurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q_9eqzw.App\\Controller\\EncadreurController::delete()'] = ($container->privates['.service_locator.Q_9eqzw'] ?? $container->load('get_ServiceLocator_Q9eqzwService'))->withContext('App\\Controller\\EncadreurController::delete()', $container);
    }
}
