<?php

namespace ContainerAq9Kqjs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncadreurControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xBM8bnR.App\Controller\EncadreurController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xBM8bnR.App\\Controller\\EncadreurController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'resetPasswordHelper' => ['privates', 'symfonycasts.reset_password.helper', 'getSymfonycasts_ResetPassword_HelperService', true],
        ], [
            'passwordHasher' => '?',
            'entityManager' => '?',
            'mailer' => '?',
            'resetPasswordHelper' => '?',
        ]))->withContext('App\\Controller\\EncadreurController::new()', $container);
    }
}
