<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BvbpfeBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BvbpfeB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BvbpfeB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'encadreur' => ['privates', '.errored..service_locator.BvbpfeB.App\\Entity\\Encadreur', NULL, 'Cannot autowire service ".service_locator.BvbpfeB": it needs an instance of "App\\Entity\\Encadreur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'encadreur' => 'App\\Entity\\Encadreur',
        ]);
    }
}
