<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MxEaS7iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MxEaS7i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MxEaS7i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'encadreurRepository' => ['privates', 'App\\Repository\\EncadreurRepository', 'getEncadreurRepositoryService', true],
        ], [
            'encadreurRepository' => 'App\\Repository\\EncadreurRepository',
        ]);
    }
}
