<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CVDkb7jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cVDkb7j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cVDkb7j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reunion' => ['privates', '.errored..service_locator.cVDkb7j.App\\Entity\\Reunion', NULL, 'Cannot autowire service ".service_locator.cVDkb7j": it needs an instance of "App\\Entity\\Reunion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reunion' => 'App\\Entity\\Reunion',
        ]);
    }
}
