<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ddr0LLAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ddr0LLA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ddr0LLA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'membresRepository' => ['privates', 'App\\Repository\\MembresRepository', 'getMembresRepositoryService', true],
        ], [
            'membresRepository' => 'App\\Repository\\MembresRepository',
        ]);
    }
}
