<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQWjt3uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fQWjt3u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fQWjt3u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reunionRepository' => ['privates', 'App\\Repository\\ReunionRepository', 'getReunionRepositoryService', true],
        ], [
            'reunionRepository' => 'App\\Repository\\ReunionRepository',
        ]);
    }
}
