<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZcZElGdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zcZElGd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zcZElGd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'theme' => ['privates', '.errored..service_locator.zcZElGd.App\\Entity\\Themes', NULL, 'Cannot autowire service ".service_locator.zcZElGd": it needs an instance of "App\\Entity\\Themes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'theme' => 'App\\Entity\\Themes',
        ]);
    }
}
