<?php

namespace ContainerDOTucxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialites2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9cO.Nmo.App\Entity\Specialites' shared service.
     *
     * @return \App\Entity\Specialites
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9cO.Nmo": it needs an instance of "App\\Entity\\Specialites" but this type has been excluded in "config/services.yaml".');
    }
}
