<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q9eqzwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q_9eqzw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q_9eqzw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'encadreur' => ['privates', '.errored..service_locator.Q_9eqzw.App\\Entity\\Encadreur', NULL, 'Cannot autowire service ".service_locator.Q_9eqzw": it needs an instance of "App\\Entity\\Encadreur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'encadreur' => 'App\\Entity\\Encadreur',
            'entityManager' => '?',
        ]);
    }
}
