<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDahirasControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4sMFoOA.App\Controller\DahirasController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4sMFoOA.App\\Controller\\DahirasController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dahira' => ['privates', '.errored..service_locator.4sMFoOA.App\\Entity\\Dahiras', NULL, 'Cannot autowire service ".service_locator.4sMFoOA": it needs an instance of "App\\Entity\\Dahiras" but this type has been excluded in "config/services.yaml".'],
        ], [
            'dahira' => 'App\\Entity\\Dahiras',
        ]))->withContext('App\\Controller\\DahirasController::show()', $container);
    }
}
