<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembresControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4cr9aWo.App\Controller\MembresController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4cr9aWo.App\\Controller\\MembresController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'membre' => ['privates', '.errored..service_locator.4cr9aWo.App\\Entity\\Membres', NULL, 'Cannot autowire service ".service_locator.4cr9aWo": it needs an instance of "App\\Entity\\Membres" but this type has been excluded in "config/services.yaml".'],
        ], [
            'membre' => 'App\\Entity\\Membres',
        ]))->withContext('App\\Controller\\MembresController::show()', $container);
    }
}
