<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembres2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jj2911m.App\Entity\Membres' shared service.
     *
     * @return \App\Entity\Membres
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Jj2911m": it needs an instance of "App\\Entity\\Membres" but this type has been excluded in "config/services.yaml".');
    }
}
