<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembresControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E6adc9U.App\Controller\MembresController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E6adc9U.App\\Controller\\MembresController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'membresRepository' => ['privates', 'App\\Repository\\MembresRepository', 'getMembresRepositoryService', true],
        ], [
            'membresRepository' => 'App\\Repository\\MembresRepository',
        ]))->withContext('App\\Controller\\MembresController::index()', $container);
    }
}
