<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembresControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jj2911m.App\Controller\MembresController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Jj2911m'] ?? $container->load('get_ServiceLocator_Jj2911mService'));

        if (isset($container->privates['.service_locator.Jj2911m.App\\Controller\\MembresController::edit()'])) {
            return $container->privates['.service_locator.Jj2911m.App\\Controller\\MembresController::edit()'];
        }

        return $container->privates['.service_locator.Jj2911m.App\\Controller\\MembresController::edit()'] = $a->withContext('App\\Controller\\MembresController::edit()', $container);
    }
}
