<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumerogeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Numerogenerator' shared autowired service.
     *
     * @return \App\Service\Numerogenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Numerogenerator.php';

        return $container->privates['App\\Service\\Numerogenerator'] = new \App\Service\Numerogenerator(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
