<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReunionControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.158Sx_t.App\Controller\ReunionController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.158Sx_t.App\\Controller\\ReunionController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reunionRepository' => ['privates', 'App\\Repository\\ReunionRepository', 'getReunionRepositoryService', true],
        ], [
            'reunionRepository' => 'App\\Repository\\ReunionRepository',
        ]))->withContext('App\\Controller\\ReunionController::index()', $container);
    }
}
