<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReunionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8U2gOPW.App\Entity\Reunion' shared service.
     *
     * @return \App\Entity\Reunion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8U2gOPW": it needs an instance of "App\\Entity\\Reunion" but this type has been excluded in "config/services.yaml".');
    }
}
