<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialitesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Fce28i.App\Controller\SpecialitesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Fce28i.App\\Controller\\SpecialitesController::delete()'] = ($container->privates['.service_locator..Fce28i'] ?? $container->load('get_ServiceLocator__Fce28iService'))->withContext('App\\Controller\\SpecialitesController::delete()', $container);
    }
}
