<?php

namespace ContainerIWXPAL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S53iC1x.App\Controller\ThemesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.S53iC1x'] ?? $container->load('get_ServiceLocator_S53iC1xService'));

        if (isset($container->privates['.service_locator.S53iC1x.App\\Controller\\ThemesController::edit()'])) {
            return $container->privates['.service_locator.S53iC1x.App\\Controller\\ThemesController::edit()'];
        }

        return $container->privates['.service_locator.S53iC1x.App\\Controller\\ThemesController::edit()'] = $a->withContext('App\\Controller\\ThemesController::edit()', $container);
    }
}
