<?php

namespace ContainerFJ5xcZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncadreur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YukPcYQ.App\Entity\Encadreur' shared service.
     *
     * @return \App\Entity\Encadreur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YukPcYQ": it needs an instance of "App\\Entity\\Encadreur" but this type has been excluded in "config/services.yaml".');
    }
}
