<?php

namespace ContainerFJ5xcZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerstateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.067pOr..App\Controller\UserController::state()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.067pOr..App\\Controller\\UserController::state()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.067pOr..App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.067pOr.": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::state()', $container);
    }
}
