<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4d7lXM3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4d7lXM3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4d7lXM3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4d7lXM3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4d7lXM3\App_KernelDevDebugContainer([
    'container.build_hash' => '4d7lXM3',
    'container.build_id' => '404f2ad0',
    'container.build_time' => 1731855224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4d7lXM3');
