<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGTAxXkV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGTAxXkV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGTAxXkV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGTAxXkV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGTAxXkV\App_KernelDevDebugContainer([
    'container.build_hash' => 'GTAxXkV',
    'container.build_id' => 'f756eb5c',
    'container.build_time' => 1731078494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGTAxXkV');
