<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAq9Kqjs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAq9Kqjs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAq9Kqjs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAq9Kqjs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAq9Kqjs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aq9Kqjs',
    'container.build_id' => '5b5120fa',
    'container.build_time' => 1729039086,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAq9Kqjs');
